Add required mail gems
Running into this error:
> LoadError:  cannot load such file -- net/pop

The solution is to require the missing gems:
https://stackoverflow.com/a/70500221

Refs: #3575