Update pending invite links
This link was throwing an error:
ActionView::Template::Error (undefined method `mentor_invites_path' for #<ActionView::Base:0x00000000079478>

This route doesn't exist, the link was incorrectly updated during the
Rails 6 upgrade. This new update will use one of these two existing
routes:

student_team_member_invite_path
mentor_team_member_invite_path

Refs: #3340