Update rake task that generates certs in batches
I ran into an error running this rake task:
```
ArgumentError: comparison of String with 0 failed
```

The `batch_size` needs to be converted to an integer for it to work.

Refs: #3899