Chore: Move copyToClipboard function to partial
This will move the copyToClipboard function to the Rails partial where
it is being used. This is to try to address these errors when including
it in admin.js:

> SyntaxError: Unexpected token: keyword (function)
> SyntaxError: Unexpected token: arrow (=>)

Refs: #4757