Chore: Update bootsnap gem
CircleCI is failing:

> LoadError: libssl.so.3: cannot open shared object file: No such file or directory - /home/circleci/technovation-girls/vendor/bundle/ruby/3.1.0/gems/puma-5.6.9/lib/puma/puma_http11.so
> /home/circleci/technovation-girls/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in
`require'

Seeing if this will fix it.

Refs: #5065